#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;

$application = new Application();

$application->add(new \Cjpgdk\Wordbook\Client\DictionariesList("dictionaries:list"));
$application->add(new \Cjpgdk\Wordbook\Client\DictionariesSearch("dictionaries:search"));
$application->add(new \Cjpgdk\Wordbook\Client\Suggestions("suggestion"));

$application->run();
